name: markdownlint

on:
  push:
    branches:
      - main

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Run mdl
      uses: actionshub/markdownlint@main
