on: pull_request
name: TOC Generator
jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/toc-generator@v2.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TOC_TITLE: "**Inhaltsverzeichnis**"
        # Git commit name.
        COMMIT_NAME: "TOCGEN"
        CREATE_PR: false
        TARGET_PATHS: "./ABWL-LEDER/README.md, ./ASM-GUENTHER/README.md, ./DBS-DORENDORF/README.md, ./PRO-KASCHE/README.md, ./SWE-KASCHE/README.md ./EMB-GUENTHER/README.md"
